### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by nevillelyh** [spotify/zoltar#1]
We should:
- [x] poms use the same style
- [x] the same use of `final`
- [x] review public APIs - which methods/classes are open
- [x] document all the public APIs
- [x] no unused imports
- [x] document that both TF and XGBoost are thread-safe

**Comment by ravwojdyla** [comment]
will take a stub at the javadocs to public APIs

**Comment by ravwojdyla** [comment]
* review public APIs - which methods/classes are open
 * document all the public APIs
 * document that both TF and XGBoost are thread-safe

was addressed in #19

**Comment by ravwojdyla** [comment]
Last set of fixes to poms is in #21
