### ISSUE TITLE
Capture prediction specific metrics

### ISSUE THREAD

**Issue by nevillelyh** [spotify/zoltar#11]
This is related to monitoring epic, we want to capture basic service runtime metrics (we should get this part for free from apollo - need to validate?) and prediction specific metrics (see list of metrics in the doc below). The MVP would be to get a dashboard with basic metrics in alien.

Monitoring RFC: https://docs.google.com/document/d/1gc1vLcwml06S-Xh3sKZK8vh_tiApxz7DxpCdpGObZwY/edit

**Comment by andrewsmartin** [comment]
Can we close this?
