### ISSUE TITLE
Upgrade TensorFlow to 1.10.0

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/zoltar#135]
https://github.com/tensorflow/tensorflow/releases/tag/v1.9.0

**Comment by regadas** [comment]
@ravwojdyla I see that your issue https://github.com/tensorflow/tensorflow/issues/21284 is still open! Should we give `1.10.0` a try and see if it has the same issue?

**Comment by ravwojdyla** [comment]
@regadas yeah, we probably should - can give it a try today.

**Comment by brianmartin** [comment]
@regadas Looks like you upgraded to 1.11.0. Closable?

**Comment by regadas** [comment]
@brianmartin yup! Closed via #155
