### ISSUE TITLE
Support model bundles

### ISSUE THREAD

**Issue by yonromai** [spotify/zoltar#144]
It's very common that folks want to load several models concurrently, as opposed to having 1 model.
Should we make it a prime citizen of the Zoltar API?

**Comment by ravwojdyla** [comment]
@yonromai could you provide more details, which parts would you like to encapsulate in the "bundle"?

**Comment by ravwojdyla** [comment]
@yonromai aha, I see - let's see what we can do.

**Comment by brianmartin** [comment]
Eagerly closing this, as we haven't seen very much interest in this feature internally. Feel free to re-open if the need arises.

**Comment by regadas** [comment]
Yeah let's reopen this if needed!
