### ISSUE TITLE
Add helper for TF predict results

### ISSUE THREAD

**Issue by nevillelyh** [spotify/zoltar#2]
Right now TF predict library returns a List of Tensors in the order of `fetch` operations, this is error prone, we should provide a helper that given a list of fetch ops, should return a map (?) of `op name` -> `Tensor`.

**Comment by nevillelyh** [comment]
Something like this?

```java
Map<String, Tensor<?>> run(Runner runner, List<String> ops) {}
```

**Comment by nevillelyh** [comment]
https://github.com/spotify/zoltar/blob/26cfa07f97fb2074482308f00523ea2b9cdb11c5/zoltar-tensorflow/src/main/java/com/spotify/zoltar/tf/Utils.java#L32

@ravwojdyla this what you have in mind?

**Comment by ravwojdyla** [comment]
@nevillelyh yea this looks good

**Comment by ravwojdyla** [comment]
the only problem - we still expose tensors - which the users have to close themselves - is there anything we could do about that?

**Comment by nevillelyh** [comment]
We can close them in the util method?

**Comment by ravwojdyla** [comment]
@nevillelyh afair - once tensor is closed, its memory is gone, so users would not be able to retrieve the values.

**Comment by nevillelyh** [comment]
We can ask user to pass in a `Map<String, Tensor<?>> -> OutputT` lambda but that feels clunky?

**Comment by ravwojdyla** [comment]
yeah, it's not great. but nothing easy comes to my mind (apart from the game of references in java).

**Comment by nevillelyh** [comment]
How about this?

- specialized `runAndExtract*` methods for `Map<String, {int[], long[], float[], double[]}>`
- generic `runAndExtract` for `Map<String, OutputTensor>` where `OutputTensor` is kind of a union type over int/long/float/double arrays

**Comment by nevillelyh** [comment]
There's also a `fetch(String op, int idx)` case we didn't cover. It'll be harder though since we need to pass in a `Map<String, Integer>`?

**Comment by ravwojdyla** [comment]
@nevillelyh the `idx` might fall into the 10% - where ppl would have to implement their own stuff. The proposal above will work for any shape of {int, long, float, double} or just a single dim?

**Comment by nevillelyh** [comment]
Yeah I'm gonna keep it simple, just a union `JTensor` type that wraps a single primitive array
