### ISSUE TITLE
Move iris dataset to data-integration-test project

### ISSUE THREAD

**Issue by fallonchen** [spotify/zoltar#37]
in `zoltar-tests` we reference`ml-sketchbook:zoltar.iris`. We should move this dataset to the public `data-integration-test` project.

**Comment by nevillelyh** [comment]
Invalid? Should we close then?

**Comment by fallonchen** [comment]
Hm, no. I didn't know what to label this with since it's not exactly a bug.

**Comment by nevillelyh** [comment]
What about making it a task of moving integration test data to the `data-integration-test` project, which we already use for scio?

**Comment by fallonchen** [comment]
Ah, perfect!
