### ISSUE TITLE
Review/improve prediction API

### ISSUE THREAD

**Issue by nevillelyh** [spotify/zoltar#6]
rav:

Get some feedback on the API for prediction, I have tried to use it myself on a completely new example, and quite quickly got confused, it's either that we need an easier API or some higher level API on top of the current building blocks.

**Comment by regadas** [comment]
This is sort of being adressed on PR #59.

**Comment by regadas** [comment]
@nevillelyh @ravwojdyla should we keep this open? or can we close it for now?

**Comment by nevillelyh** [comment]
:+1: can re-open or create a new one if there's more to do.
