### ISSUE TITLE
maven fails with zoltar-tests test-jar not generated at compile time on fresh env.

### ISSUE THREAD

**Issue by regadas** [spotify/zoltar#72]

**Comment by andrewsmartin** [comment]
We can probably work around this by building the test-jar during the compile phase instead of requiring a pre-run of `install` but this feels a bit hacky?

**Comment by andrewsmartin** [comment]
This wouldn't completely fix the problem because `zoltar-api` still needs test classes from `zoltar-tensorflow` and `zoltar-xgboost`, but could we move `IrisHelper` from `src/test` into `src/main`? Since it's a test module feels like helper code like that should go in main? WDYT?

**Comment by regadas** [comment]
@andrewsmartin yup let's move it to `src/main`.

**Comment by regadas** [comment]
@andrewsmartin you taking it?
