### ISSUE TITLE
Provide BOM

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/zoltar#97]
Right now there is multitude of conflicts between dependencies in common cases of mixing scio, featran, zoltar and apollo. For most of our sbt projects where we don't enforce enforcer - it's less of a "problem" (or should i see we are just postponing the problem), in most maven we do enforce it tho. It might be worth to provide a BOM for zoltar so that ppl can include it in their dependency management and get zoltar with fixed dependencies for combined zoltar+scio+featran+apollo.

**Comment by regadas** [comment]
@ravwojdyla glad that you brought this up again! I'll take a stab at this since it might fix one of the problems that we have.

**Comment by ravwojdyla** [comment]
@regadas you can take a look [here](https://ghe.spotify.net/ml/ml-paved-road-serving/blob/master/pom.xml) for some inspiration.
